/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author oscar
 */
public class ViewEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmpleados
     */
    public ViewEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtf_buscar_empleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_empleados = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jtf_colonia_empleado = new javax.swing.JTextField();
        jtf_rfc_empleado = new javax.swing.JTextField();
        jtf_apm_empleado = new javax.swing.JTextField();
        jtf_telefono_empleado = new javax.swing.JTextField();
        jb_reporte = new javax.swing.JButton();
        jtf_app_empleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jb_actualizar = new javax.swing.JButton();
        jtf_calle_empleado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_numero_empleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jb_eliminar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jtf_nombre_empleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jb_cancelar = new javax.swing.JButton();
        jtf_id_empleado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jb_anterior = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 175, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier-tool (1).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 40, -1));

        jLabel8.setBackground(new java.awt.Color(254, 254, 254));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("EMPLEADOS");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));
        add(jtf_buscar_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, 229, 20));

        jt_empleados.setAutoCreateRowSorter(true);
        jt_empleados.setBackground(new java.awt.Color(254, 254, 254));
        jt_empleados.setBorder(null);
        jt_empleados.setFont(new java.awt.Font("AnjaliOldLipi", 0, 15)); // NOI18N
        jt_empleados.setForeground(new java.awt.Color(254, 254, 254));
        jt_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido  Paterno", "Apellido Materno", "Calle", "Numero", "Colonia ", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_empleados.setOpaque(false);
        jt_empleados.setSelectionBackground(new java.awt.Color(46, 125, 50));
        jScrollPane1.setViewportView(jt_empleados);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 1210, 120));

        jLabel12.setFont(new java.awt.Font("AnjaliOldLipi", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Buscar");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 70, -1));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_nuevo.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(46, 125, 50));
        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        jb_nuevo.setText("Nuevo ");
        jb_nuevo.setBorderPainted(false);
        jb_nuevo.setContentAreaFilled(false);
        jPanel2.add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, -1, -1));

        jtf_colonia_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_colonia_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_colonia_empleado.setBorder(null);
        jPanel2.add(jtf_colonia_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 229, 20));

        jtf_rfc_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_rfc_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_rfc_empleado.setBorder(null);
        jPanel2.add(jtf_rfc_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 229, 20));

        jtf_apm_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_apm_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_apm_empleado.setBorder(null);
        jPanel2.add(jtf_apm_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 229, 20));

        jtf_telefono_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_telefono_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_telefono_empleado.setBorder(null);
        jPanel2.add(jtf_telefono_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 229, 20));

        jb_reporte.setBackground(new java.awt.Color(76, 175, 80));
        jb_reporte.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_reporte.setForeground(new java.awt.Color(46, 125, 50));
        jb_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf1.png"))); // NOI18N
        jb_reporte.setText("Reporte");
        jb_reporte.setBorderPainted(false);
        jb_reporte.setContentAreaFilled(false);
        jPanel2.add(jb_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, -1, -1));

        jtf_app_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_app_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_app_empleado.setBorder(null);
        jPanel2.add(jtf_app_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 229, 20));

        jLabel3.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 125, 50));
        jLabel3.setText("Apellido Paterno");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, -1));

        jb_actualizar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_actualizar.setForeground(new java.awt.Color(46, 125, 50));
        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exchange.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.setBorderPainted(false);
        jb_actualizar.setContentAreaFilled(false);
        jPanel2.add(jb_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 60, -1, -1));

        jtf_calle_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_calle_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_calle_empleado.setBorder(null);
        jPanel2.add(jtf_calle_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 229, 20));

        jLabel6.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(46, 125, 50));
        jLabel6.setText("Colonia ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 150, -1));

        jLabel4.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 125, 50));
        jLabel4.setText("Telefono");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 150, -1));

        jtf_numero_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_numero_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_numero_empleado.setBorder(null);
        jPanel2.add(jtf_numero_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 229, 20));

        jLabel9.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 125, 50));
        jLabel9.setText("ID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 85, -1));

        jLabel7.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(46, 125, 50));
        jLabel7.setText("Numero");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 150, -1));

        jLabel2.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 125, 50));
        jLabel2.setText("Nombre ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 85, -1));

        jLabel10.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 125, 50));
        jLabel10.setText("Apellido Materno");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, -1));

        jLabel11.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 125, 50));
        jLabel11.setText("Calle");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 150, -1));

        jb_eliminar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(46, 125, 50));
        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/del.png"))); // NOI18N
        jb_eliminar.setText("Elimiar");
        jb_eliminar.setBorderPainted(false);
        jb_eliminar.setContentAreaFilled(false);
        jPanel2.add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, -1, -1));

        jb_guardar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(46, 125, 50));
        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/disquette.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.setBorderPainted(false);
        jb_guardar.setContentAreaFilled(false);
        jPanel2.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 120, -1, -1));

        jtf_nombre_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_nombre_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_nombre_empleado.setBorder(null);
        jtf_nombre_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombre_empleadoActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 229, 20));

        jLabel5.setFont(new java.awt.Font("Loma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 125, 50));
        jLabel5.setText("RFC");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 150, -1));

        jb_cancelar.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        jb_cancelar.setForeground(new java.awt.Color(46, 125, 50));
        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/x-button.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.setBorderPainted(false);
        jb_cancelar.setContentAreaFilled(false);
        jPanel2.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 180, -1, -1));

        jtf_id_empleado.setBackground(new java.awt.Color(254, 254, 254));
        jtf_id_empleado.setForeground(new java.awt.Color(46, 125, 50));
        jtf_id_empleado.setBorder(null);
        jtf_id_empleado.setCaretColor(new java.awt.Color(2, 119, 189));
        jtf_id_empleado.setOpaque(false);
        jPanel2.add(jtf_id_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 229, 20));

        jSeparator1.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 230, 20));

        jSeparator2.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator2.setToolTipText("");
        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 230, 20));

        jSeparator3.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator3.setToolTipText("");
        jSeparator3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 230, 20));

        jSeparator4.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator4.setToolTipText("");
        jSeparator4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 20));

        jSeparator5.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator5.setToolTipText("");
        jSeparator5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 230, 20));

        jSeparator6.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator6.setToolTipText("");
        jSeparator6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, 20));

        jSeparator7.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator7.setToolTipText("");
        jSeparator7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 230, 20));

        jSeparator8.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator8.setToolTipText("");
        jSeparator8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 230, 20));

        jSeparator9.setForeground(new java.awt.Color(46, 125, 50));
        jSeparator9.setToolTipText("");
        jSeparator9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 230, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 1210, 300));

        jb_anterior.setBackground(new java.awt.Color(34, 59, 75));
        jb_anterior.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic1on.png"))); // NOI18N
        jb_anterior.setBorderPainted(false);
        jb_anterior.setContentAreaFilled(false);
        add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, -1, -1));

        jb_primero.setBackground(new java.awt.Color(34, 59, 75));
        jb_primero.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        jb_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/previous.png"))); // NOI18N
        jb_primero.setBorderPainted(false);
        jb_primero.setContentAreaFilled(false);
        add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jb_siguiente.setBackground(new java.awt.Color(34, 59, 75));
        jb_siguiente.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        jb_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon.png"))); // NOI18N
        jb_siguiente.setBorderPainted(false);
        jb_siguiente.setContentAreaFilled(false);
        add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        jb_ultimo.setBackground(new java.awt.Color(34, 59, 75));
        jb_ultimo.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        jb_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/next-track.png"))); // NOI18N
        jb_ultimo.setBorderPainted(false);
        jb_ultimo.setContentAreaFilled(false);
        add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombre_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombre_empleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombre_empleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JButton jb_actualizar;
    public javax.swing.JButton jb_anterior;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_primero;
    public javax.swing.JButton jb_reporte;
    public javax.swing.JButton jb_siguiente;
    public javax.swing.JButton jb_ultimo;
    public javax.swing.JTable jt_empleados;
    public javax.swing.JTextField jtf_apm_empleado;
    public javax.swing.JTextField jtf_app_empleado;
    public javax.swing.JTextField jtf_buscar_empleado;
    public javax.swing.JTextField jtf_calle_empleado;
    public javax.swing.JTextField jtf_colonia_empleado;
    public javax.swing.JTextField jtf_id_empleado;
    public javax.swing.JTextField jtf_nombre_empleado;
    public javax.swing.JTextField jtf_numero_empleado;
    public javax.swing.JTextField jtf_rfc_empleado;
    public javax.swing.JTextField jtf_telefono_empleado;
    // End of variables declaration//GEN-END:variables
}
